### ISSUE TITLE
Refresh control capability

### ISSUE THREAD

**Issue by harrisonas18** [OfTheWolf/TwitterProfile#1]
This library has been excellent. Except there is no ability to add a refresh control to the scroll views. I would like to be able to refresh my feeds with the refresh control. Is there a way to do this?

**Comment by OfTheWolf** [comment]
@harrisonas18 I am glad you liked it.
 
I added tp_scrollViewDidLoad to TPProgressDelegate to obtain the overlayScrollView. So you can use it to add refreshController or whatever reason. I already added implementation to the Example project with UIRefreshControl but you can use other libraries such as MJRefresh or custom.   

See updated `TPProgressDelegate`:
```
public protocol TPProgressDelegate{
    func tp_scrollView(_ scrollView: UIScrollView, didUpdate progress: CGFloat)
    
    //New method to get overlayScrollView 
    func tp_scrollViewDidLoad(_ scrollView: UIScrollView)
}
```
