### ISSUE TITLE
Tap geustrue of UIView back button is not fired

### ISSUE THREAD

**Issue by dobiho5** [OfTheWolf/TwitterProfile#13]
Thanks for your awesome library. 

I have a question how to get tap event from view back button on viewController.swift 
![Simulator_Screen_Shot_-_iPhone_Xs_-_2020-06-20_at_10_52_37](https://user-images.githubusercontent.com/19466316/85188792-45b50400-b2e4-11ea-91ca-f06f810445c2.png)

I made iboutlet for UIView, and get tap gesture. But UIView do not fire tap gesture.

When I put UIView on Headerviewcontroller , it is fired.  How can I get this UIView tap gesture fired? Please help me. Thanks in advance. 

    @IBOutlet weak var viewBackBtn: UIView!

     override func viewDidLoad() {
        super.viewDidLoad()

       viewBackBtn.isUserInteractionEnabled = true
        let tap: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(didBackBtnTapped(_ :)))
        tap.numberOfTouchesRequired = 1
        viewBackBtn.addGestureRecognizer(tap)
    }

**Comment by OfTheWolf** [comment]
@dobiho5 
You are right. ContainerVC is in front of it. So You can not tap. You can bring your views to front to be able to tap it.
` view.bringSubviewToFront(viewBackBtn)
`

**Comment by dobiho5** [comment]
@OfTheWolf
Wow! It works. 
Thanks you for your quick response and great code.
