### ISSUE TITLE
EffectView Stuck when change the tabbar

### ISSUE THREAD

**Issue by oguzveozturk** [OfTheWolf/TwitterProfile#15]
<img width="287" alt="Screen Shot 2020-07-09 at 15 58 02" src="https://user-images.githubusercontent.com/54209230/87043109-44993780-c1fd-11ea-8311-159046003592.png">

first off all thanks for the effort, much appreciated it!
and also efectview stucking when change the tabBar. any idea?

**Comment by OfTheWolf** [comment]
Hey oğuz thanks. it must be related to #14. See this for a possible solution https://stackoverflow.com/a/58028231/5923606. If it doesn't work, please provide me a minimal project that replicates this issue.

**Comment by oguzveozturk** [comment]
<img width="642" alt="Screen Shot 2020-07-09 at 23 04 23" src="https://user-images.githubusercontent.com/54209230/87085454-94e1bb00-c238-11ea-98a2-6de9f84a4904.png">

solved it this way. thanks again. now i just need the more dynamic value then "0.43" : )
