### ISSUE TITLE
No scrolling - When using a scrollview in Bottom controller in your sample project.

### ISSUE THREAD

**Issue by prashantAlgante** [OfTheWolf/TwitterProfile#18]
When using Scrollview  instead of table view in bottom view controller  then scrolling is not happening properly in Container scroll view.

Point 2 - also the content size of bottom screen is not getting calculated correct in your Container class when using above case.

See image . Red portion is scroll view inside every tab.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-08-11 at 19 20 25](https://user-images.githubusercontent.com/66359785/89906054-85bfa580-dc08-11ea-912f-699ce935d835.png)

**Comment by OfTheWolf** [comment]
If you set content size of the bottom scroll view it must work. Table view updates its content size as you scroll but scroll view does'nt.
