### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by Xhale1** [OfTheWolf/TwitterProfile#2]
Incredible project, it's the only one I've found that properly solves the whole layered scroll view issue.

The one issue I've found is that when a user taps the status bar on the top of the screen, the entire view shifts down a bit instead of scrolling to top. Clicking twice properly scrolls to top. I'm unsure of how to fix this as I'm not as familiar with the project structure as you are.

**Comment by OfTheWolf** [comment]
You can disable master scrollView status bar tap gesture. See below.

 ```
 class MasterViewController : UIViewController, UIScrollViewDelegate {
...
    override func loadView() {
        scrollView = UIScrollView()
        scrollView.scrollsToTop = false  //disable status bar gesture 
```

**Comment by Xhale1** [comment]
Beautiful, it works like a charm!
