### ISSUE TITLE
Cannot touch the overlayScrollView indicators

### ISSUE THREAD

**Issue by AndyWu-developer** [OfTheWolf/TwitterProfile#30]
When setting the overlayScrollView's showsVerticalScrollIndicator to true, I can see the indicator, but cannot touch it. Anyway to work around that? Thanks

**Comment by AndyWu-developer** [comment]
Fixed it, simply add the overlay scollView after everything else is added to the view.

**Comment by binaryloader** [comment]
@andywpt 

Hi, if you add the overlayScrollView behind the containerScrollView, tap and gesture actions do not work. Can you explain in more detail how you resolved this issue?
