### ISSUE TITLE
How to reload header size?

### ISSUE THREAD

**Issue by Chareef17** [OfTheWolf/TwitterProfile#7]
I have a problem when dynamic header's height.

**Comment by OfTheWolf** [comment]
@Chareef17 @maxkillpo I added a new branch for dynamic header development. It may need some extra work. I am working on it. Please refer to "feature/dynamic_header".

**Comment by OfTheWolf** [comment]
@Chareef17 @maxkillpo i added dynamic height header support with 1.0.0 version. You can try it.

**Comment by maxkillpo** [comment]
very good work!!! @OfTheWolf
