### ISSUE TITLE
pod install

### ISSUE THREAD

**Issue by maxkillpo** [OfTheWolf/TwitterProfile#9]
pod 'TwitterProfile' , '1.0.0' Not ready install

**Comment by supplementler-ugur** [comment]
any error message? you can try pod update without version maybe.

**Comment by OfTheWolf** [comment]
@maxkillpo what error message did you get? you can try pod update without version maybe.

**Comment by OfTheWolf** [comment]
I suppose you fixed your problem. so i close the issue. you can open it anytime if you experience it again.
